### ISSUE TITLE
Organização de pacotes

### ISSUE THREAD

**Issue by RennanSilvaCosta** [Rafaela-Teixeira/SENAC#1]
Percebi que organização dos pacotes está meio confusa, tendo vários projetos no mesmo lugar, ou projetos dentro de projetos.
Estava pensando em organizar, todas as classes (exercícios) em um único projeto, e separar as matérias em pacotes, e colocar as atividades correspondentes no pacote.

Então fazer pacotes com as siglas das aulas
* AP (Algoritmo e programação)
* PI (Projeto Integrador)

E fazer sub pacotes com as atividades.
E dentro desses sub pacotes colocar as classes com os exercícios e etc.

#### O que acha?

Algo parecido com isso: 
![Capturar](https://user-images.githubusercontent.com/45303056/120397216-489ae000-c30e-11eb-8179-1e8c5a0b0070.PNG)

**Comment by Rafaela-Teixeira** [comment]
Rennan, boa noite!

Adorei as dicas, quando puder, podemos marcar um call?

**Comment by RennanSilvaCosta** [comment]
@Rafaela-Teixeira Bom dia,

Podemos sim, até o domingo (18/07), estou livre o dia todo, me chame quando quiser.
